version: '3'
services:
  nginx:
    container_name: v-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./project-tools/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  mysql:
    container_name: v-mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./project-tools/mysql/data:/var/lib/mysql
      - ./project-tools/mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: boot
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    command: mysqld
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET NAMES utf8mb4;'
      --innodb-flush-log-at-trx-commit=0
      --explicit_defaults_for_timestamp=true
      --default-authentication-plugin=mysql_native_password

  redis:
    container_name: v-redis
    image: redis:5.0.5
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./project-tools/redis/data:/data

  app:
    build: ./
    working_dir: /app
    restart: always
    expose:
      - "8888"
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    depends_on:
      - mysql
      - redis
    command: mvn clean spring-boot:run
