version: '3'
services:
  nginx:
    container_name: v-nginx
    image: nginx:1.13
    restart: always
    networks:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./project-tools/nginx/conf.d:/etc/nginx/conf.d

  mysql:
    container_name: v-mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wang-yan-boot
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    command: mysqld
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET NAMES utf8mb4;'
      --innodb-flush-log-at-trx-commit=0
      --explicit_defaults_for_timestamp=true
      --default-authentication-plugin=mysql_native_password
    networks:
      - app
    ports:
      - "3306:3306"
    volumes:
      - ./project-tools/mysql/data:/var/lib/mysql
      - ./project-tools/mysql/conf:/etc/mysql/conf.d
    restart: always

  redis:
    container_name: v-redis
    image: redis:5.0.5
    networks:
      - app
    ports:
      - "6379:6379"
    volumes:
      - ./project-tools/redis/data:/data
      - ./project-tools/redis/conf:/usr/local/etc/redis/redis.conf

  app:
    restart: always
    build: ./
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    networks:
      - app
    expose:
      - "8080"
    depends_on:
      - nginx
      - mysql
      - redis
    command: mvn clean spring-boot:run
networks:
  app:
    external: true
# 配置日志驱动的相关参数
logging:
  driver: syslog
options:
  max-size: "200k"
  max-file: "10"

